AWSTemplateFormatVersion: 2010-09-09
Description: This Template will create a ec2 Instance using parameters
Parameters:
#### String Parameters ####
  MyAvailabilityZone:
    Description: Select the AvailabilityZone
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b

  MyInstanceType:
    Description: Select the InstanceType from the list
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.medium

  MySubnetId:
    Description: Select the SubnetId from the list
    Type: String
    Default: subnet-Id_1
    AllowedValues:
      - subnet-Id_1
      - subnet-Id_2

### CommaDelimitedList Parameter it is useful when you need to provide multiple values for a single property ####
  MySecurityGroupIds:
    Description: Comma-delimited list of three SecurityGroupIds
    Type: CommaDelimitedList
    Default: sg-Id_1, sg-Id_2
    
Resources:
  JenkinsEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-02b91a46e15da2494
      InstanceType: !Ref MyInstanceType
      KeyName: my_work
      AvailabilityZone: !Ref MyAvailabilityZone
      SecurityGroupIds: !Ref MySecurityGroupIds
      SubnetId: !Ref MySubnetId
      Tags:
        - Key: Name
          Value: Jenkins-Terraform-VM
        - Key: Owner
          Value: DevOps-Team